name: Deploy ​Documentation​

on:
  ​push​:
    branches​:
      - '​main​'
      - 'dev'
    ​paths​:
      - ​**.md
      - "mkdocs.yml"
jobs:
  build​:
    runs-on​: ​ubuntu-latest​
    ​steps​:
      - ​uses​: ​actions/checkout@v2
      - ​uses​: ​actions/setup-python@v2​
        with:
          python-version: '3.9'
      - name: Installs pip
        run: pip install --upgrade pip && pip install mkdocstrings && pip install mkdocs mkdocs-gen-files
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - ​name​: ​Publish docs​
        ​run​: mkdocs gh-deploy

